name: Core CI

on:
  push:
    branches:
      - main
      - next

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0
    - name: Setup Go environment
      uses: actions/setup-go@v2.1.5
      with:
        go-version: ^1.17
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v2.5.2
      with:
        args: --enable gofmt,govet,gocyclo,ineffassign,misspell
    - name: test
      run: go test -race -coverprofile=coverage.out ./...
    - name: actions-goveralls
      uses: shogo82148/actions-goveralls@v1.5.1
      with:
        path-to-profile: coverage.out
